name: Update and Deploy

on:
  schedule:
    - cron: "30 5 * * *"  # Esegui ogni giorno alle 05:30
  workflow_dispatch:        # Permette di avviare manualmente il workflow

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Git
      - name: Set up Git
        run: |
          git config --global user.name "Marco"
          git config --global user.email "20mark@gmail.com"

      # Esegui lo script di aggiornamento
      - name: Run update script
        run: bash ./update_and_deploy.sh

      # Avvia il deploy su Render utilizzando tutte le variabili segrete
      - name: Trigger Render Deploy for first URL
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_URL }}
